"""darwinloop report.py — Markdown evolution report builder."""

from __future__ import annotations

from darwinloop._models import EvolutionResult


def build_markdown_report(result: EvolutionResult) -> str:
    """Build a full markdown evolution report.

    Args:
        result: The :class:`~darwinloop._models.EvolutionResult` to report on.

    Returns:
        Markdown string.
    """
    lines: list[str] = []

    # Header
    lines += [
        "# darwinloop Evolution Report",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Base score | {result.base_score:.2f} |",
        f"| Best score | {result.best_score:.2f} |",
        f"| Improvement | +{result.score_delta:.2f} ({result.score_delta*100:.0f}pp) |",
        f"| Best agent | {result.best_agent_id} |",
        f"| Best generation | {result.best_generation} |",
        f"| Total agents evaluated | {result.total_agents} |",
        f"| Valid agents | {result.valid_agents} |",
        f"| Iterations run | {result.iterations_run} |",
        "",
    ]

    # Score timeline
    lines += ["## Score Timeline", ""]
    for g in result.generations:
        bar_len = int(g.score * 20)
        bar = "█" * bar_len + "░" * (20 - bar_len)
        status = "✓" if g.is_valid else "✗"
        lines.append(f"- `{g.agent_id}` {status} `{bar}` **{g.score:.2f}**  _{g.proposal[:60]}_")
    lines.append("")

    # Family tree (text)
    lines += ["## Family Tree", "", "```"]
    by_gen: dict[int, list] = {}
    for g in result.generations:
        by_gen.setdefault(g.generation, []).append(g)

    for gen_num in sorted(by_gen):
        for g in by_gen[gen_num]:
            indent = "  " * gen_num
            star = " ⭐" if g.agent_id == result.best_agent_id else ""
            lines.append(f"{indent}{g.agent_id} (score={g.score:.2f}){star}")
    lines += ["```", ""]

    # Per-generation details
    lines += ["## Generation Details", ""]
    for g in result.generations:
        lines += [
            f"### {g.agent_id}  (gen {g.generation}, score {g.score:.2f})",
            f"- **Parent**: {g.parent_id or '— (base)'}",
            f"- **Proposal**: {g.proposal}",
            f"- **Valid**: {'Yes' if g.is_valid else 'No'}",
            "",
        ]

    # Diff
    diff = result.diff
    if diff:
        lines += [
            "## Code Diff (original → best evolved)",
            "",
            "```diff",
            diff,
            "```",
            "",
        ]
    else:
        lines += ["## Code Diff", "", "_No changes — base agent was already optimal._", ""]

    lines += [
        "---",
        "_Generated by [darwinloop](https://github.com/fetchai/darwinloop)_",
    ]

    return "\n".join(lines)
