"""darwinloop scaffold.py — Auto-generate benchmark tasks from agent code."""

from __future__ import annotations

import re
from pathlib import Path

_TEMPLATE = '''\
"""
Auto-generated benchmark tasks for {filename}.
Generated by darwinloop scaffold.

Edit these tasks, then run:
    darwinloop evolve {filename} --tasks benchmarks.py --iterations 5
"""

from darwinloop import BenchmarkTask

TASKS = [
    BenchmarkTask(
        id="task_001",
        name="basic_happy_path",
        description="Most common query should return a valid result",
        input="What is the current status?",
        expected="",  # TODO: fill in expected output substring
    ),
    BenchmarkTask(
        id="task_002",
        name="edge_case_empty",
        description="Empty or minimal input should not crash",
        input="",
        expected="",
    ),
    BenchmarkTask(
        id="task_003",
        name="follow_up_context",
        description="Follow-up question should use context from previous turn",
        input_sequence=[
            "Tell me about the main topic",
            "Give me more details",
        ],
        expected="",  # TODO: fill in
    ),
]
'''

_LLM_PROMPT = """\
Read the following Python agent code and generate 10 BenchmarkTask objects that test
its most critical behaviours. Cover:
1. Happy path (most common queries)
2. Edge cases (unusual input, abbreviations, typos)
3. Follow-up context (multi-turn pronoun/reference resolution)
4. Known failure modes (based on the code structure)
5. Negative assertions (things the output must NOT contain)

Agent code:
```python
{code}
```

Output a valid Python file with:
- imports: `from darwinloop import BenchmarkTask`
- a list called `TASKS` containing 10 BenchmarkTask instances
- each task has id, name, description, input or input_sequence, expected, and optionally must_not_contain

Output ONLY the Python code, no explanation.
"""


def generate_benchmarks(
    target: str,
    model: str = "asi1",
    dry_run: bool = False,
) -> str:
    """Generate benchmark task code from *target* agent file.

    Args:
        target: Path to the agent Python file to analyse.
        model: LLM model to use for generation.
        dry_run: Return a template without calling the LLM.

    Returns:
        Python source code string for a ``benchmarks.py`` file.
    """
    path = Path(target)
    filename = path.name

    if dry_run or not path.exists():
        return _TEMPLATE.format(filename=filename)

    code = path.read_text(encoding="utf-8")

    from darwinloop.llm.client import get_llm_client
    llm = get_llm_client(model=model)

    history = llm.chat_with_tools(  # type: ignore[union-attr]
        instruction=_LLM_PROMPT.format(code=code[:6000]),
        tools=[],
        tool_functions={},
        logging_fn=lambda _: None,
    )

    # Extract last assistant message
    for msg in reversed(history):
        if msg.get("role") == "assistant":
            content = msg.get("content", "")
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        raw = block["text"]
                        return _extract_code(raw, filename)
            elif isinstance(content, str):
                return _extract_code(content, filename)

    return _TEMPLATE.format(filename=filename)


def _extract_code(text: str, filename: str) -> str:
    """Strip markdown fences and ensure the output is valid Python."""
    # Try to extract code from ```python ... ``` block
    m = re.search(r"```python\s*(.*?)```", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    m = re.search(r"```\s*(.*?)```", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    # Return as-is if no fences
    if "BenchmarkTask" in text:
        return text.strip()
    return _TEMPLATE.format(filename=filename)
